Release ibgateway-latest@10.25.1j
Signed-off-by: gnzsnz <8376642+gnzsnz@users.noreply.github.com>

diff --git a/.github/workflows/detect-releases.yml b/.github/workflows/detect-releases.yml
--- a/.github/workflows/detect-releases.yml
+++ b/.github/workflows/detect-releases.yml
@@ -64,6 +64,39 @@ jobs:
         if: ${{ steps.check-update.outputs.has_update == 'true' }}
         run: ./update.sh ${{ matrix.channel }} ${{ steps.version.outputs.build_version }}
 
+      - name: Update README
+        if: ${{ steps.check-update.outputs.has_update == 'true' }}
+        run: |
+          # get stable and latest versions
+          _stable_dockerfile='stable/Dockerfile'
+          _latest_dockerfile='latest/Dockerfile'
+          if [ ${{ matrix.channel }} = 'latest']; then
+            # set latest
+            LATEST_VERSION=${{ steps.version.outputs.build_version }}
+            LATEST_MINOR=$(echo $LATEST_VERSION | cut -d '.' -f1,2)
+
+            # set stable
+            STABLE_VERSION=$(grep 'ENV IB_GATEWAY_VERSION=' $_stable_dockerfile | head -1 | cut -d '=' -f2)
+            STABLE_MINOR=$(echo $STABLE_VERSION| cut -d '.' -f1,2)
+
+          elif [ ${{ matrix.channel }} = 'stable']; then
+            # set STABLE
+            STABLE_VERSION=${{ steps.version.outputs.build_version }}
+            STABLE_MINOR=$(echo $STABLE_VERSION | cut -d '.' -f1,2)
+            # set LATEST
+            LATEST_VERSION=$(grep 'ENV IB_GATEWAY_VERSION=' $_latest_dockerfile | head -1 | cut -d '=' -f2)
+            LATEST_MINOR=$(echo $STABLE_VERSION| cut -d '.' -f1,2)
+          else
+            echo "invalid channel: ${{ matrix.channel }}"
+            exit 1
+          fi
+          # IBC
+          IBC_VERSION="$(grep 'ENV IBC_VERSION' Dockerfile.template|cut -d '=' -f 2)"
+          # show in log
+          echo "$LATEST_VERSION,$LATEST_MINOR,$STABLE_VERSION,$STABLE_MINOR,$IBC_VERSION"
+          # replace variables
+          envsubst '$LATEST_VERSION,$LATEST_MINOR,$STABLE_VERSION,$STABLE_MINOR,$IBC_VERSION' < template_README.md > README.md
+
       - name: Create PR
         if: ${{ steps.check-update.outputs.has_update == 'true' }}
         env:
@@ -74,7 +107,7 @@ jobs:
           git config user.email github-actions@github.com
           git pull
           git checkout -b "$t_branch" origin/master
-          git add '${{ matrix.channel }}'
+          git add '${{ matrix.channel }}' README.md
           git commit -m 'Update `${{ matrix.channel }}` to `${{ steps.version.outputs.build_version }}`'
           git push --set-upstream origin "$t_branch"
 
